export const HIRAGANA_DATA = [
  // Vokale (Lektion 1 - erste Zeichen in Minna no Nihongo)
  { char: "あ", rom: "a", group: "vowels", lesson: 1 },
  { char: "い", rom: "i", group: "vowels", lesson: 1 },
  { char: "う", rom: "u", group: "vowels", lesson: 1 },
  { char: "え", rom: "e", group: "vowels", lesson: 1 },
  { char: "お", rom: "o", group: "vowels", lesson: 1 },
  // K-Reihe
  { char: "か", rom: "ka", group: "k", lesson: 1 },
  { char: "き", rom: "ki", group: "k", lesson: 1 },
  { char: "く", rom: "ku", group: "k", lesson: 1 },
  { char: "け", rom: "ke", group: "k", lesson: 1 },
  { char: "こ", rom: "ko", group: "k", lesson: 1 },
  // S-Reihe
  { char: "さ", rom: "sa", group: "s", lesson: 1 },
  { char: "し", rom: "shi", group: "s", lesson: 1 },
  { char: "す", rom: "su", group: "s", lesson: 1 },
  { char: "せ", rom: "se", group: "s", lesson: 1 },
  { char: "そ", rom: "so", group: "s", lesson: 1 },
  // T-Reihe
  { char: "た", rom: "ta", group: "t", lesson: 1 },
  { char: "ち", rom: "chi", group: "t", lesson: 1 },
  { char: "つ", rom: "tsu", group: "t", lesson: 1 },
  { char: "て", rom: "te", group: "t", lesson: 1 },
  { char: "と", rom: "to", group: "t", lesson: 1 },
  // N-Reihe
  { char: "な", rom: "na", group: "n", lesson: 1 },
  { char: "に", rom: "ni", group: "n", lesson: 1 },
  { char: "ぬ", rom: "nu", group: "n", lesson: 1 },
  { char: "ね", rom: "ne", group: "n", lesson: 1 },
  { char: "の", rom: "no", group: "n", lesson: 1 },
  // H-Reihe
  { char: "は", rom: "ha", group: "h", lesson: 1 },
  { char: "ひ", rom: "hi", group: "h", lesson: 1 },
  { char: "ふ", rom: "fu", group: "h", lesson: 1 },
  { char: "へ", rom: "he", group: "h", lesson: 1 },
  { char: "ほ", rom: "ho", group: "h", lesson: 1 },
  // M-Reihe
  { char: "ま", rom: "ma", group: "m", lesson: 1 },
  { char: "み", rom: "mi", group: "m", lesson: 1 },
  { char: "む", rom: "mu", group: "m", lesson: 1 },
  { char: "め", rom: "me", group: "m", lesson: 1 },
  { char: "も", rom: "mo", group: "m", lesson: 1 },
  // Y-Reihe
  { char: "や", rom: "ya", group: "y", lesson: 1 },
  { char: "ゆ", rom: "yu", group: "y", lesson: 1 },
  { char: "よ", rom: "yo", group: "y", lesson: 1 },
  // R-Reihe
  { char: "ら", rom: "ra", group: "r", lesson: 1 },
  { char: "り", rom: "ri", group: "r", lesson: 1 },
  { char: "る", rom: "ru", group: "r", lesson: 1 },
  { char: "れ", rom: "re", group: "r", lesson: 1 },
  { char: "ろ", rom: "ro", group: "r", lesson: 1 },
  // W-Reihe + n
  { char: "わ", rom: "wa", group: "w", lesson: 1 },
  { char: "を", rom: "wo", group: "w", lesson: 1 },
  { char: "ん", rom: "n", group: "w", lesson: 1 },
  // Dakuten (stimmhaft) – typischerweise später in Minna no Nihongo
  { char: "が", rom: "ga", group: "g", lesson: 2 },
  { char: "ぎ", rom: "gi", group: "g", lesson: 2 },
  { char: "ぐ", rom: "gu", group: "g", lesson: 2 },
  { char: "げ", rom: "ge", group: "g", lesson: 2 },
  { char: "ご", rom: "go", group: "g", lesson: 2 },
  { char: "ざ", rom: "za", group: "z", lesson: 2 },
  { char: "じ", rom: "ji", group: "z", lesson: 2 },
  { char: "ず", rom: "zu", group: "z", lesson: 2 },
  { char: "ぜ", rom: "ze", group: "z", lesson: 2 },
  { char: "ぞ", rom: "zo", group: "z", lesson: 2 },
  { char: "だ", rom: "da", group: "d", lesson: 2 },
  { char: "ぢ", rom: "di", group: "d", lesson: 2 },
  { char: "づ", rom: "du", group: "d", lesson: 2 },
  { char: "で", rom: "de", group: "d", lesson: 2 },
  { char: "ど", rom: "do", group: "d", lesson: 2 },
  { char: "ば", rom: "ba", group: "b", lesson: 2 },
  { char: "び", rom: "bi", group: "b", lesson: 2 },
  { char: "ぶ", rom: "bu", group: "b", lesson: 2 },
  { char: "べ", rom: "be", group: "b", lesson: 2 },
  { char: "ぼ", rom: "bo", group: "b", lesson: 2 },
  { char: "ぱ", rom: "pa", group: "p", lesson: 2 },
  { char: "ぴ", rom: "pi", group: "p", lesson: 2 },
  { char: "ぷ", rom: "pu", group: "p", lesson: 2 },
  { char: "ぺ", rom: "pe", group: "p", lesson: 2 },
  { char: "ぽ", rom: "po", group: "p", lesson: 2 },
];

export const WORD_DATA = [
  // Begrüßungen und Ausdrücke
  { word: "すみません", rom: "sumimasen", german: "Entschuldigung / Tut mir leid", lesson: 1 },
  { word: "おはよう", rom: "ohayou", german: "Guten Morgen", lesson: 1 },
  { word: "こんにちは", rom: "konnichiwa", german: "Guten Tag", lesson: 1 },
  { word: "さようなら", rom: "sayounara", german: "Auf Wiedersehen", lesson: 1 },
  { word: "おやすみ", rom: "oyasumi", german: "Gute Nacht", lesson: 1 },
  { word: "はい", rom: "hai", german: "Ja", lesson: 1 },
  { word: "いいえ", rom: "iie", german: "Nein", lesson: 1 },
  // Personen
  { word: "わたし", rom: "watashi", german: "ich", lesson: 1 },
  { word: "あなた", rom: "anata", german: "du", lesson: 1 },
  { word: "かれ", rom: "kare", german: "er", lesson: 1 },
  { word: "ひと", rom: "hito", german: "Person", lesson: 1 },
  { word: "おんな", rom: "onna", german: "Frau", lesson: 1 },
  { word: "おとこ", rom: "otoko", german: "Mann", lesson: 1 },
  { word: "せんせい", rom: "sensei", german: "Lehrer", lesson: 1 },
  // Tiere
  { word: "いぬ", rom: "inu", german: "Hund", lesson: 1 },
  { word: "ねこ", rom: "neko", german: "Katze", lesson: 1 },
  { word: "さかな", rom: "sakana", german: "Fisch", lesson: 1 },
  // Essen und Natur
  { word: "のみもの", rom: "nomimono", german: "Getränk", lesson: 1 },
  { word: "やさい", rom: "yasai", german: "Gemüse", lesson: 1 },
  // Körper
  { word: "て", rom: "te", german: "Hand", lesson: 1 },
  { word: "あし", rom: "ashi", german: "Fuß", lesson: 1 },
  { word: "め", rom: "me", german: "Auge", lesson: 1 },
  { word: "みみ", rom: "mimi", german: "Ohr", lesson: 1 },
  { word: "はな", rom: "hana", german: "Nase", lesson: 1 },
  { word: "くち", rom: "kuchi", german: "Mund", lesson: 1 },
  { word: "あたま", rom: "atama", german: "Kopf", lesson: 1 },
  // Zahlen
  { word: "いち", rom: "ichi", german: "eins", lesson: 1 },
  { word: "に", rom: "ni", german: "zwei", lesson: 1 },
  { word: "さん", rom: "san", german: "drei", lesson: 1 },
  { word: "よん", rom: "yon", german: "vier", lesson: 1 },
  { word: "ろく", rom: "roku", german: "sechs", lesson: 1 },
  { word: "なな", rom: "nana", german: "sieben", lesson: 1 },
  { word: "はち", rom: "hachi", german: "acht", lesson: 1 },
  // Fragewörter und Sonstiges
  { word: "なに", rom: "nani", german: "was", lesson: 1 },
  { word: "いくら", rom: "ikura", german: "wie viel / wie teuer", lesson: 1 },
  { word: "たいへん", rom: "taihen", german: "sehr / schlimm", lesson: 1 },
  // Alltagsgegenstände und Orte
  { word: "ほん", rom: "hon", german: "Buch", lesson: 1 },
  { word: "かさ", rom: "kasa", german: "Regenschirm", lesson: 1 },
  { word: "くるま", rom: "kuruma", german: "Auto", lesson: 1 },
  { word: "ひこうき", rom: "hikouki", german: "Flugzeug", lesson: 1 },
  { word: "ふね", rom: "fune", german: "Schiff", lesson: 1 },
  { word: "いす", rom: "isu", german: "Stuhl", lesson: 1 },
  { word: "つくえ", rom: "tsukue", german: "Tisch", lesson: 1 },
  { word: "とけい", rom: "tokei", german: "Uhr", lesson: 1 },
  { word: "くつ", rom: "kutsu", german: "Schuhe", lesson: 1 },
  { word: "ふく", rom: "fuku", german: "Kleidung", lesson: 1 },
  { word: "こうえん", rom: "kouen", german: "Park", lesson: 1 },
  { word: "まち", rom: "machi", german: "Stadt", lesson: 1 },
  { word: "みせ", rom: "mise", german: "Geschäft", lesson: 1 },
  { word: "いま", rom: "ima", german: "jetzt", lesson: 1 },
  { word: "あさ", rom: "asa", german: "Morgen", lesson: 1 },
  { word: "ひる", rom: "hiru", german: "Mittag", lesson: 1 },
  { word: "よる", rom: "yoru", german: "Nacht", lesson: 1 },
  { word: "いえ", rom: "ie", german: "Haus", lesson: 1 },
  { word: "うち", rom: "uchi", german: "Zuhause", lesson: 1 },
];

export const GROUP_LABELS = {
  vowels: "Vokale",
  k: "か行 (K)",
  s: "さ行 (S)",
  t: "た行 (T)",
  n: "な行 (N)",
  h: "は行 (H)",
  m: "ま行 (M)",
  y: "や行 (Y)",
  r: "ら行 (R)",
  w: "わ行 (W) · ん",
  g: "が行 (G)",
  z: "ざ行 (Z)",
  d: "だ行 (D)",
  b: "ば行 (B)",
  p: "ぱ行 (P)",
};
